graph LR
    A((Start<br/>t=0)) --> B((Math Layer<br/>t=1))
    A --> C((Physics Layer<br/>t=1))
    A --> D((Historical Layer<br/>t=1))
    
    B --> E((Fibonacci Gen<br/>t=2))
    B --> F((Chaos Theory<br/>t=2))
    B --> G((Vector Space<br/>t=2))
    
    C --> H((Spectral<br/>t=2))
    C --> I((Doppler<br/>t=2))
    
    D --> J((Medieval<br/>t=2))
    D --> K((Renaissance<br/>t=2))
    D --> L((Baroque<br/>t=2))
    D --> M((Modern<br/>t=2))
    
    E --> N((Rhythm Matrix<br/>t=3))
    F --> N
    G --> O((Harmonic Field<br/>t=3))
    
    H --> P((Timbre Control<br/>t=3))
    I --> P
    
    J --> Q((Organum Proc<br/>t=3))
    K --> R((Motet Proc<br/>t=3))
    L --> S((Fugue Proc<br/>t=3))
    M --> T((Serial Proc<br/>t=3))
    
    N --> U((Temporal Sync<br/>t=4))
    O --> U
    P --> U
    Q --> U
    R --> U
    S --> U
    T --> U
    
    U --> V((Art Integration<br/>t=5))
    V --> W((Impressionism<br/>t=6))
    V --> X((Art Deco<br/>t=6))
    V --> Y((Avant-garde<br/>t=6))
    
    W --> Z((Visual-Audio Map<br/>t=7))
    X --> Z
    Y --> Z
    
    Z --> AA((Poetry Rhythm<br/>t=8))
    Z --> AB((Dance Motion<br/>t=8))
    Z --> AC((Comedy Timing<br/>t=8))
    
    AA --> AD((Final Synthesis<br/>t=9))
    AB --> AD
    AC --> AD
    
    AD --> AE((MIDI Gen<br/>t=10))
    AE --> AF((Score Gen<br/>t=11))
    AF --> AG((End<br/>t=12))
